### ISSUE TITLE
Unable to start tau

### ISSUE THREAD

**Issue by dillfrescott** [taubyte/tau#140]
```shell
root@cloud1:~# tau start -s compute
panic: listen tcp 0.0.0.0:80: bind: address already in use

goroutine 1128 [running]:
github.com/taubyte/tau/protocols/substrate.(*Service).startHttp.func1()
        /home/runner/work/tau/tau/protocols/substrate/http.go:53 +0x8c
created by github.com/taubyte/tau/protocols/substrate.(*Service).startHttp in goroutine 1
        /home/runner/work/tau/tau/protocols/substrate/http.go:44 +0x246
```

**Comment by dillfrescott** [comment]
I checked and nothing is using port 80 at all. this is a fresh machine.

**Comment by dillfrescott** [comment]
Ok it seems even when able to start I am met with many more errors just trying to get this project to work at all.

```shell
2024-04-25T06:21:21.443Z        ERROR   p2p.streams.client      client/client.go:283    starting stream to `12D3KooWNM6bG8guSQMvK6SaUyn9qYt6d3ka9xvfR5pC4hTtsbcF`;`/seer/v1` failed with: %!w(*fmt.wrapError=&{failed to negotiate protocol: protocols not supported: [/seer/v1] {[/seer/v1]}})
```

No matter what I do it is just unable to work it seems :(

**Comment by dillfrescott** [comment]
My bad I managed to get it to work. It just took a bit!

**Comment by Kisaragi-ng** [comment]
> My bad I managed to get it to work. It just took a bit!

if you don't mind, how'd you managed to get it to work?

I'm stuck with the same error, both the doc and error output doesn't help at all
